### ISSUE TITLE
Bug in trV/E for cloning

### ISSUE THREAD

**Issue by dominicbarnes** [mhelvens/graph.js#15]
Because of how `graph.clone()` has it's arguments set up, passing **only** a `trV` argument causes `trE` to use the exact same function. I don't think this was the intended behavior, as I expected `trE` to continue to use it's own identity function.

For example:

```js
let graph = new Graph();

graph.addVertex('a', 'a'); // value: a
graph.addVertex('b', 'b'); // value: b
graph.addEdge('a', 'b');   // no value

// clone as uppercase
graph.clone(v => v.toUpperCase()); // throws!
```

It throws because it attempts to call `v.toUpperCase()` on the edge's value, which is `undefined`.

This is caused by `trE=trV` in the function's definition, whereas it should probably be `trE=(v=>v)` to keep from conflicting.

Currently, my workaround is to always specify a function for both `trV` *and* `trE`.

**Comment by mhelvens** [comment]
This is actually intended behavior, and (I thought) clearly documented:

    a custom transformation function for values stored in edges; defaults to the function given for trV

My reasoning was that it would be more common to translate all values the same way than to treat vertex and edge values differently. This also makes it possible to treat both cases differently in the same function (by testing for a second key). Finally, it seemed easy enough to add `v=>v` as a third argument.

But if you'd like to make a case for changing this behavior in the next version, be my guest.
