### ISSUE TITLE
Using edge weights in a path search

### ISSUE THREAD

**Issue by molp** [mhelvens/graph.js#16]
Hi,

this project looks very promising and has a super nice API! So far I could not find out though how to use edge weights to find multiple paths between two vertices ordered by the weights. In our application we need to find the shortest paths between two vertices and a list with alternative routes with increasingly longer paths.

Any plans on implementing this or pointers on where one would start to do so?

Thanks!

**Comment by mhelvens** [comment]
Glad you like the library!

This can definitely be done, but it seems a bit too specific to be a part of the core library. (There are already one or two algorithms in there that should be extracted: #8.)

There is already [an iterator](https://github.com/mhelvens/graph.js#Graph+paths) to go over all paths between two vertices. You can extract exactly as many paths as you want, and then sort them based on any criteria you like. You can compute the length of a single path with something like this (not tested):

    var length = path.slice(1).reduce(
        ([len, v1], v2) => [len + graph.edgeValue(v1, v2), v2],
        [0, path[0]]
    )[0];
