### ISSUE TITLE
Module shows up as insecure on NSP (culprit is babel dep)

### ISSUE THREAD

**Issue by dominicbarnes** [mhelvens/graph.js#18]
There is a security vulnerability in the babel dependency:
 - https://nodesecurity.io/advisories/118

I've tried locally to update babel to v6, but the tests fail and I've not yet discovered the source of the issue. I will dig deeper tonight and hopefully have a PR to address this.

For context, I'm depending on this library for a project I'm working on, and would like to resolve all the NSP advisories throughout my dependencies.

**Comment by dominicbarnes** [comment]
Ah right, the migration path between babel 5 and 6 is significant.

Does babel need to be a [dependency](https://github.com/mhelvens/graph.js/blob/master/package.json#L25) at all? (it looks like it may only need to be a dev dep)

**Comment by mhelvens** [comment]
Marking this as fixed by merging your pull request.
