### ISSUE TITLE
Shortest path

### ISSUE THREAD

**Issue by iosonosempreio** [mhelvens/graph.js#21]
Hi,
is there any way for getting the shortest path between two nodes?
Thanks!

**Comment by mhelvens** [comment]
Hiya. There's currently no shortest path algorithm built into the library. To be honest, the algorithms that *are* built in have simply been those that I needed for my own work when I built the library. For the next version, I'll put non-trivial algorithms in a separate module (#8), and shortest path will surely be among them.

For now, you'll have to write your own. If you do, and are willing to write unit tests and docs for it, I'd be happy to accept a pull request.

**Comment by iosonosempreio** [comment]
hi @mhelvens and thanks for your reply.
I had to switch to a different library: [http://jsnetworkx.org/](http://jsnetworkx.org/) Not as straightforward as yours is, but features the algorithms I needed.
