### ISSUE TITLE
using graph.js in Node

### ISSUE THREAD

**Issue by anvk** [mhelvens/graph.js#3]
Does your library even work in Node ?

It is available as NPM package sure. But there is no documentation on how to use it in Node.js at all.

**Comment by mhelvens** [comment]
Definitely. graph.js is just an advanced data-structure, and does nothing that is specific to browsers. The only difference is in the way to import the library. Here's how to do it in Node:

```JavaScript
var Graph = require('graph.js/dist/<file>');
```

Where `<file>` is [one of these](https://github.com/mhelvens/graph.js#files), depending on whether you want to load the required [Babel polyfill](https://babeljs.io/docs/usage/polyfill/) separately. Node.js does not yet support ES6 syntax, so the `.es6.js` option is out.

I agree that this should be more clear from the docs. I'll fix this soon. Thanks!

**Comment by anvk** [comment]
Oh I see. I'm going to give a try tomorrow and close this issue. Thanks a lot for such a quick reply.

In the meantime, do you support functionality to check if the directed graph is acyclic? I have a simple problem of finding if I have a loop in my graph. Finding a graph library to do so is a challenge.

**Comment by anvk** [comment]
Works like a charm!!

`Graph = require('graph.js/dist/graph.full.js');`

Thanks a lot for your help.
Your NPM module is beautiful! I managed to find cycles in my directed graph.
Also the code quality of your ES6 is superb!

Great job on this module/

**Comment by mhelvens** [comment]
Thanks! I love ES6. So many useful additions to the language.

**Comment by mhelvens** [comment]
I improved the documentation in 7d7213430156dad1978b1c8602d3b4ad0cecbac4. Hopefully this helps others in the future.

**Comment by anvk** [comment]
That looks so much better!
It is a pain to find a good Graph lib in NPM. It is either does not work, or it has NO documentation, or it is overly simple, or it lacks some details and does not work right out of the box(graph.js example since I was trying to understand what I should require)

BTW I saw this in your documentation `npm install delta.js --save` 
did you mean `npm install graph.js --save`

**Comment by mhelvens** [comment]
Ha! Thanks, nice catch. Fixed in dd11e784e6d556ea5b34c69f54946990b39289e1.

**Comment by anvk** [comment]
Also a quick question - is babel a devDependency and not a dependency (in package.json) ?
Because I assumed that it is there to compile ES6->ES5 which means there is no real dependency for graph.js (it is written in ES6 and does not rely on other modules really)

**Comment by mhelvens** [comment]
You're partially correct. Babel is used to compile the code, but it also provides a required runtime polyfill, for additions to the standard library. The standalone version of graph.js includes these additions, but the other version does not.

A few months ago, this polyfill was removed from the `babel` package, only to remain in the `babel-core` package. So that one should actually be the runtime dependency. Thanks! (efa0c638af9d3ab8a4f56f1a216d645f6a23ddd0)
