### ISSUE TITLE
Ability to find all cycles in the graph

### ISSUE THREAD

**Issue by anvk** [mhelvens/graph.js#4]
Just wondering if it is easy to implement. Currently `cycle()` returns only one random cycle found in the graph.

**Comment by anvk** [comment]
Also maybe return a set of edges which form a cycle.

It could be an object cycle which contains Edges and Vertices. You could also add a function to print out the path. For example: [A, edge1, B, edge2, C, edge3, A]

**Comment by mhelvens** [comment]
Until now I've only been interested in eliminating cycles. Once a cycle'd been found, there was no need to look further. :-)

But yeah, I could definitely create a `cycles` iterator, to iterate over all cycles. It's quite a small change to the current algorithm, actually.

As for the edges in a cycle, those can be inferred easily from the vertices, e.g., `graph.edgeValue(cycle[0], cycle[1])`.

**Comment by anvk** [comment]
Well I'm also interested in eliminating cycles. But I have a more complex problem.

Imagine you have cycles:
A->B->A
C->B->A->C

Now imagine that you have to skip on the first cycle. You want to keep it in your system (the edge B to A is special). If I run `cycle()` then I would always get A->B->A. If I remove the last edge (technique to loop through possible cycles using your library) then I would skip second cycle and it would be left undetectable.

If the function would return all possible cycles then I would be able just ignore first cycle and take care of the second one (remove A->C edge)

**Comment by mhelvens** [comment]
OK. Try out version 1.16. It has a `cycles()` iterator now.

I've added a number of unit-tests, but if you could also try it out on a number of different cases, that would be appreciated!

**Comment by mhelvens** [comment]
PS: If you don't like the somewhat clunky ES5 syntax I'm recommending for ES6-style iterators, you might consider a library like [wu.js](https://fitzgen.github.io/wu.js/), which makes it a bit less painful. For example:

    wu(graph.cycles()).forEach(function (cycle) {
        /* use cycle */
    });

**Comment by anvk** [comment]
Hey. thanks for the change, I will give it a shot.
I'm pretty sure that arrays allow `forEach` in node. If result is an array of cycles then I can simply do

```
var cycles = graph.cycles;
cycles.forEach(function(cycle) {
    /* use cycle */
});
```

**Comment by mhelvens** [comment]
That's just it. The method *doesn't* return an array. It returns an [iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_iterator_protocol). That's why I'm mentioning wu.js.

Iterators are a lot more elegant for this kind of thing, because they'll only compute the next value if and when you need it.

**Comment by anvk** [comment]
Well I would personally avoid any extra packages unless I really need them. So far I can use the loop you provided in the example.

I ran your new function on my problem and it worked nicely... although I got lots of duplicates. Will try to make a smaller example which would reproduce this.

**Comment by mhelvens** [comment]
Great, thanks!

**Comment by anvk** [comment]
I'm sorry I was not able to create a simple example. I only have a complicated example.

https://gist.github.com/anvk/f3b48a84b3f3a0fe8244

I included test data and an output of it.

**Comment by mhelvens** [comment]
Thanks! I'll try and have a look. If, in the meantime, you do come up with a minimal example, that would be most welcome.

**Comment by mhelvens** [comment]
I found the problem. It happens when there are multiple distinct paths leading to the same cycle:

```javascript
graph = new Graph(
	[['n1', 'n2']],
	[['n2', 'n3']],
	[['n2', 'n6']],
	[['n6', 'n3']],
	[['n3', 'n4']],
	[['n4', 'n5']],
	[['n5', 'n4']]
);

// n1 ──▶ n2 ───▶ n3 ──▶ n4 ──▶ n5
//        ╷       ▲      ▲      ╷
//        ╰─▶ n6 ─╯      ╰──────╯
```

Working on a solution.

**Comment by mhelvens** [comment]
OK, try version 1.17.1, and let me know how it goes.

It turns out my algorithm was a bit too naive. I'm now using the Tarjan algorithm:

[Enumeration of the elementary circuits of a directed graph
R. Tarjan, SIAM Journal on Computing, 2 (1973), pp. 211-216](http://dx.doi.org/10.1137/0202017)

In the future, this should be replaced with the more efficient version by Johnson:

[Finding all the elementary circuits of a directed graph.
D. B. Johnson, SIAM Journal on Computing 4, no. 1, 77-84, 1975](http://dx.doi.org/10.1137/0204007)

**Comment by anvk** [comment]
Nice ! Worked like a charm.
Yeah any optimization on cycle detection is a plus since it really depends on how complex is your graph.

Thanks a lot for implementing this. So far I was not able to reproduce any errors. Should we close this Issue ?

**Comment by mhelvens** [comment]
Yep. Thanks for your feedback.

(PS: If you want, perhaps you could have a look at issue #7, and leave your thoughts during the next few weeks.)

**Comment by anvk** [comment]
For sure. If I have few weeks ahead to think about it...
Will give my feedback on this matter.

Thanks again !
