### ISSUE TITLE
Maybe also add functions EdgesFrom and EdgesTo

### ISSUE THREAD

**Issue by anvk** [mhelvens/graph.js#5]
Show list of edges which go into node and go out

**Comment by mhelvens** [comment]
Have you found these: [.verticesFrom](https://github.com/mhelvens/graph.js#Graph#verticesFrom), [.verticesTo](https://github.com/mhelvens/graph.js#Graph#verticesTo)?

What do you need that these methods cannot already do?

**Comment by anvk** [comment]
Ah sorry about that. I took a closer look into the methods you provide and I think I can find out what I'm looking into.

**Comment by mhelvens** [comment]
I'll close the issue for now. If you need more, come back and comment.
